### ISSUE TITLE
Why is the Shortest Path implemented in Array instead of a Map ??

### ISSUE THREAD

**Issue by fadi-botros** [mAlaliSy/AlgoLizer-algorithms-visualizer#1]
https://github.com/mAlaliSy/AlgoLizer-algorithms-visualizer/blob/b38e7f2a5d8c3bf93eb3907db9f1ddcf34ecd3f4/app/src/main/java/com/malalisy/algolizer/domain/shortestpath/ShortestPathAlgorithmRunner.kt#L12

**Comment by mAlaliSy** [comment]
You are right, the grid can be implemented with a map of pair of integers representing the horizontal and vertical position of a tile.  Map<Pair<Int, Int>, TileType>
I will consider refactoring it when I have time.

Feel free to reopen the issue if I misunderstood your idea. Thanks!
