### ISSUE TITLE
Stacks can be easier implemented using recursion

### ISSUE THREAD

**Issue by fadi-botros** [mAlaliSy/AlgoLizer-algorithms-visualizer#2]
https://github.com/mAlaliSy/AlgoLizer-algorithms-visualizer/blob/b38e7f2a5d8c3bf93eb3907db9f1ddcf34ecd3f4/app/src/main/java/com/malalisy/algolizer/domain/shortestpath/ShortestPathAlgorithmRunner.kt#L76

**Comment by mAlaliSy** [comment]
Can you clarify your idea?

The idea here is that each node has its predecessor, we want to get the solution path in order from source to destination. So we have to reverse the path we get by going from destination to its predecessor and so on (let's call this path as reversed path).

I have thought about it and I have come up with a better solution by simply using  LinkedList, iterating through the reversed path and adding each node to the beginning of the list:

while (temp.parent != null) {
            linkedList.addFirst(temp.position)
            temp = temp.parent!!
}

**Comment by fadi-botros** [comment]
A function that calls itself can make the same effect of a LinkedList (maybe better because it would use the real stack, not in the heap (the heap in Java/Kotlin is Garbage Collected so you can't deallocate it, so anything you allocate it increases the chance of an `OutOfMemoryException` to happen)).

So, your function would be refactored in something like that (as I understand, I maybe wrong in the algorithm, so please think it in the same terms (a function that calls itself)):
```kotlin
    fun add(shortestPathNode: ShortestPathNode, toList: MutableList<Pair<Int, Int>>) {
        if (shortestPathNode.parent != null) {
            // If there is a parent, call the function itself with it BEFORE adding the element
            // because you want the reverse.
            // This function will keep calling itself until the parent == null, then the stack would
            // unwind.
            add(shortestPathNode.parent, toList)
        }
        toList.add(shortestPathNode.position)
    }

    fun findSolution(node: ShortestPathNode) {
        val sol = mutableListOf<Pair<Int, Int>>()
        var temp = node
        add(node, sol)
        this.solution = sol
        this.solutionCost = node.cost
    }
```

If we imagine the following:
```
first.parent = second
second.parent = third
third.parent = fourth
```

The code above will do the following:

```
add(first, sol)
|---> which will call add(second, sol)
    |---> which will call add(third, sol)
        |---> which will call add(fourth, sol)
            |---> fourth.parent == null, so will not call `add` in this time
            |---> but instead, will append the `fourth.position` to the `sol`, then return
        |---> back to the `add(third, sol)`, this will append the `third.position` to the `sol`, then return
    |---> back to the `add(second, sol)`, this will append the `second.position` to the `sol`, then return
|---> back to the `add(first, sol)`, this will append the `first.position` to the `sol`, then return

sol would be now = [fourth.position, third.position, second.position, first.position]
```
with less memory allocated on the Java heap, and I think with better performance

**Comment by mAlaliSy** [comment]
You don't have to explain what recursion means ^_^

I have thought about the same technique in the function you wrote yesterday while driving home before I see your comment ^_^

But recursion overhead is way much expensive than iteration approach.
Refer to https://stackoverflow.com/questions/2651112/is-recursion-ever-faster-than-looping?noredirect=1&lq=1
In recursion, each function call requires to allocate a new stack frame for the function, which has its own data, refer to https://www.artima.com/insidejvm/ed2/jvm8.html

Feel free to reopen the issue if you have any comments.

**Comment by fadi-botros** [comment]
@mAlaliSy Good point, because I thought of this from real languages prespective (C++/Swift/Rust), but didn't imagine that JVM allocates a big stack frame for each calling, and never imagined that stack frames are allocated in the JVM (in C/C++/Swift/Rust just a stack pointer is subtracted, then any data needed to be set is set).
And your function is a special case because you use a `Stack`, so I thought instead of manually using a stack we would use the system stack itself (but I didn't imagine that the JVM is implemented this very bad way, I think in C/C++/Swift/Rust and maybe GoLang also, recursion is much better **_in this particular function_**, because using the system stack which is just a pointer subtraction, is better than allocating a `Stack` data structure on the heap).
Iteration is faster than recursion when you don't really need a stack, but when you need a stack, I think recursion would be better and faster (but not in the JVM languages)

Anyway, it seems that `Stack` data structure in Java is implemented with a `Vector`, which is effectively an array, so it MAY be good and fast.
